# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- usr/ahk2hi/wip

pool:
  vmImage: 'windows-2019'

steps:
- task: UniversalPackages@0
  inputs:
    command: 'download'
    downloadDirectory: '$(System.DefaultWorkingDirectory)'
    feedsToUse: 'internal'
    vstsFeed: '63767f55-d4ed-4b12-b77e-0c9f2f118fd6/1a6eb10a-625f-49ea-8622-2421069b506b'
    vstsFeedPackage: 'd0f4d5d1-d896-4781-90b8-cc01ed6f9bf4'
    vstsPackageVersion: '0.0.1'

- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    dir
    rustup-init.exe -y --default-toolchain stable
    echo "##vso[task.setvariable variable=PATH;]%PATH%;%USERPROFILE%\.cargo\bin"
  displayName: Windows install rust

- script: cargo build --release
  displayName: Cargo build

