# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- usr/ahk2hi/wip

pool:
  vmImage: 'windows-2019'

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    az artifacts universal download --organization "https://dev.azure.com/BOSCH-CM-ESO/" --project "63767f55-d4ed-4b12-b77e-0c9f2f118fd6" --scope project --feed "Build-Tools-Sandbox" --name "rustup" --version "0.0.1" --path .
    dir
    rustup-init.exe -y --default-toolchain stable
    echo "##vso[task.setvariable variable=PATH;]%PATH%;%USERPROFILE%\.cargo\bin"
  displayName: Windows install rust

- script: cargo build --release
  displayName: Cargo build

